config/routes.rb
AssociationAppRails3::Application.routes.draw do
  resources :kine

  resources :farmers

  get "admin/admin_login"

  get "admin/admin_view"
  get "admin" => 'admin#admin_test'

  resources :users

end

app/models/cow.rb
class Cow < ActiveRecord::Base
  belongs_to :farmer
  attr_accessible :farmer_id
  # attr_accessible :title, :body
end

app/models/farmer.rb
class Farmer < ActiveRecord::Base
  attr_accessible :name

  has_many :kine
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :admin

  validates :username, presence: true
  validate :username_format

  def username_format
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :admin_check, only: ['admin_test']

  def admin_check
    # @user = User.all[1] # just using the first user
    # if @user.admin
    #   redirect_to "/admin/admin_view"
    # else
    #   redirect_to "/admin/admin_login"
    # end
  end

  def admin_test
  end

  def admin_login
  end

  def admin_view
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  # GET /farmers
  # GET /farmers.json
  def index
    @farmers = Farmer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @farmers }
    end
  end

  # GET /farmers/1
  # GET /farmers/1.json
  def show
    @farmer = Farmer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @farmer }
    end
  end

  # GET /farmers/new
  # GET /farmers/new.json
  def new
    @farmer = Farmer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @farmer }
    end
  end

  # GET /farmers/1/edit
  def edit
    @farmer = Farmer.find(params[:id])
  end

  # POST /farmers
  # POST /farmers.json
  def create
    @farmer = Farmer.new(params[:farmer])

    respond_to do |format|
      if @farmer.save
        format.html { redirect_to @farmer, notice: 'Farmer was successfully created.' }
        format.json { render json: @farmer, status: :created, location: @farmer }
      else
        format.html { render action: "new" }
        format.json { render json: @farmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /farmers/1
  # PUT /farmers/1.json
  def update
    @farmer = Farmer.find(params[:id])

    respond_to do |format|
      if @farmer.update_attributes(params[:farmer])
        format.html { redirect_to @farmer, notice: 'Farmer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @farmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farmers/1
  # DELETE /farmers/1.json
  def destroy
    @farmer = Farmer.find(params[:id])
    @farmer.destroy

    respond_to do |format|
      format.html { redirect_to farmers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/kine_controller.rb
class KineController < ApplicationController
  # GET /kine
  # GET /kine.json
  def index
    @kine = Cow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kine }
    end
  end

  # GET /kine/1
  # GET /kine/1.json
  def show
    @cow = Cow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cow }
    end
  end

  # GET /kine/new
  # GET /kine/new.json
  def new
    @cow = Cow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cow }
    end
  end

  # GET /kine/1/edit
  def edit
    @cow = Cow.find(params[:id])
  end

  # POST /kine
  # POST /kine.json
  def create
    @cow = Cow.new(params[:cow])

    respond_to do |format|
      if @cow.save
        format.html { redirect_to @cow, notice: 'Cow was successfully created.' }
        format.json { render json: @cow, status: :created, location: @cow }
      else
        format.html { render action: "new" }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kine/1
  # PUT /kine/1.json
  def update
    @cow = Cow.find(params[:id])

    respond_to do |format|
      if @cow.update_attributes(params[:cow])
        format.html { redirect_to @cow, notice: 'Cow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kine/1
  # DELETE /kine/1.json
  def destroy
    @cow = Cow.find(params[:id])
    @cow.destroy

    respond_to do |format|
      format.html { redirect_to kine_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/kine_helper.rb
module KineHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admin_login.html.erb
<h1>Admin#admin_login</h1>
<p>you aren't an admin :(</p>

app/views/admin/admin_view.html.erb
<h1>Admin#admin_view</h1>
<p>yay you are an admin</p>

app/views/admin/test.html.erb
test

app/views/farmers/_form.html.erb
<%= form_for(@farmer) do |f| %>
  <% if @farmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@farmer.errors.count, "error") %> prohibited this farmer from being saved:</h2>

      <ul>
      <% @farmer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/farmers/edit.html.erb
<h1>Editing farmer</h1>

<%= render 'form' %>

<%= link_to 'Show', @farmer %> |
<%= link_to 'Back', farmers_path %>

app/views/farmers/index.html.erb
<h1>Listing farmers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @farmers.each do |farmer| %>
  <tr>
    <td><%= farmer.name %></td>
    <td><%= link_to 'Show', farmer %></td>
    <td><%= link_to 'Edit', edit_farmer_path(farmer) %></td>
    <td><%= link_to 'Destroy', farmer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Farmer', new_farmer_path %>

app/views/farmers/new.html.erb
<h1>New farmer</h1>

<%= render 'form' %>

<%= link_to 'Back', farmers_path %>

app/views/farmers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @farmer.name %>
</p>


<%= link_to 'Edit', edit_farmer_path(@farmer) %> |
<%= link_to 'Back', farmers_path %>

app/views/kine/_form.html.erb
<%= form_for(@cow) do |f| %>
  <% if @cow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cow.errors.count, "error") %> prohibited this cow from being saved:</h2>

      <ul>
      <% @cow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :farmer %><br />
    <%= f.text_field :farmer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kine/edit.html.erb
<h1>Editing cow</h1>

<%= render 'form' %>

<%= link_to 'Show', @cow %> |
<%= link_to 'Back', kine_path %>

app/views/kine/index.html.erb
<h1>Listing kine</h1>

<table>
  <tr>
    <th>Farmer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kine.each do |cow| %>
  <tr>
    <td><%= cow.farmer %></td>
    <td><%= link_to 'Show', cow %></td>
    <td><%= link_to 'Edit', edit_cow_path(cow) %></td>
    <td><%= link_to 'Destroy', cow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cow', new_cow_path %>

app/views/kine/new.html.erb
<h1>New cow</h1>

<%= render 'form' %>

<%= link_to 'Back', kine_path %>

app/views/kine/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Farmer:</b>
  <%= @cow.farmer %>
</p>


<%= link_to 'Edit', edit_cow_path(@cow) %> |
<%= link_to 'Back', kine_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssociationAppRails3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.admin ? 'Admin' : 'Not Admin' %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>